### ISSUE TITLE
Problem with calendar extension recurrence

### ISSUE THREAD

**Issue by orlioto** [distriqt/ANE-ZzishSDK#1]
Hi,
I'm using your calendar extension and am trying to set an event to show every day. I'm looking for some ideas why is this not working and how to fix it.
It is a simple app that adds an event one minute after current time and when I add the recurrence code event doesn't show at all.
OS is Android 5.0.1, device is LG Nexus 4

Using this code:
var r:Recurrence = new Recurrence();
r.endCount = 5;
r.interval = 1;
r.frequency = Recurrence.FREQUENCY_DAILY;
e.recurrenceRules.push( r );

It look like it breaks the extension.
Any ideas? Any help will be appreciated!

Thank you very much!
All the best
Orlin

**Comment by marchbold** [comment]
Please post in the Calendar ANE repository.
