### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by frankiehex** [distriqt/ANE-ZzishSDK#2]
If I need to use PushNotifications ane 

How can I use？

**Comment by marchbold** [comment]
Please post your questions in the PushNotifications repository.

**Comment by frankiehex** [comment]
My question is
I have to buy a whole pack of ane where I'm going to download?

**Comment by marchbold** [comment]
Have a look at the site: http://airnativeextensions.com/ You only have to buy the extension you're interested in.
